AWSTemplateFormatVersion: '2010-09-09'
Description: 'Setup IAM role for EC2 instance to enable SSM'

Parameters:
  EC2InstanceId:
    Type: String
    Description: 'EC2 Instance ID to attach the IAM role to'

Resources:
  # IAM Role for EC2 to use SSM
  EC2SSMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2SSMRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Path: /

  # IAM Instance Profile
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EC2SSMInstanceProfile
      Roles:
        - !Ref EC2SSMRole

Outputs:
  InstanceProfileArn:
    Description: 'ARN of the created instance profile'
    Value: !GetAtt EC2InstanceProfile.Arn
    Export:
      Name: !Sub '${AWS::StackName}-InstanceProfileArn'
